
############################## navigation ##############################
[[main]]
name = "Produkte"
URL = "products/"
weight = 1

[[main]]
name = "Blog"
URL = "blog/"
weight = 2

[[main]]
name = "FAQ"
URL = "faq/"
weight = 3

[[main]]
name = "Kontakt"
URL = "contact/"
weight = 4

############# footer menu #############
[[footer]]
name = "Produkte"
URL = "products/"
weight = 1

[[footer]]
name = "Blog"
URL = "blog/"
weight = 2

[[footer]]
name = "FAQ"
URL = "faq/"
weight = 3

[[footer]]
name = "Allgemeine Geschäftsbedingungen"
URL = "terms-conditions/"
weight = 4

[[footer]]
name = "Kontakt"
URL = "Contact/"
weight = 5
